[package]
name = "synth-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
glob = "0.3.1"
midi-control = "0.2.2"
rodio = "0.19.0"
serialport = { version = "4.5.1", default-features = false }
