[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
    "-C", "link-arg=--sysroot=./cross-build-deps/aarch64/",
]

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    # "-C", "link-arg=--sysroot=./cross-build-deps/armv7/",
]

[target.armv7-unknown-linux-musleabihf]
# linker = "arm-linux-gnueabihf-gcc"
linker = "arm-linux-musleabihf-gcc"
rustflags = [
    "-C", "link-arg=--sysroot=./cross-build-deps/armv7/",
]

[target.x64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# [unstable]
# codegen-backend = true
#
# [profile.dev]
# codegen-backend = "cranelift"
#
# [profile.dev.package."*"]
# codegen-backend = "llvm"


